{{/*
Standard Helm helper library.
Naming, labels, and selector helpers — kept compatible with the patterns
generated by `helm create` so a reviewer's eye doesn't have to recalibrate.
*/}}

{{- define "phoenix-liveview.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "phoenix-liveview.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "phoenix-liveview.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Selector labels — kept STABLE across upgrades. Never add values that change
between releases (image tag, build sha) to selectorLabels; that breaks
rollouts because Deployment.spec.selector is immutable.
*/}}
{{- define "phoenix-liveview.selectorLabels" -}}
app.kubernetes.io/name: {{ include "phoenix-liveview.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{/*
Full label set — includes the selector labels plus identifiers that are safe
to mutate (chart version, app version, managed-by).
*/}}
{{- define "phoenix-liveview.labels" -}}
helm.sh/chart: {{ include "phoenix-liveview.chart" . }}
{{ include "phoenix-liveview.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/component: liveview
app.kubernetes.io/part-of: phoenix-liveview
{{- with .Values.commonLabels }}
{{ toYaml . }}
{{- end }}
{{- end -}}

{{- define "phoenix-liveview.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
{{- default (include "phoenix-liveview.fullname" .) .Values.serviceAccount.name -}}
{{- else -}}
{{- default "default" .Values.serviceAccount.name -}}
{{- end -}}
{{- end -}}

{{/*
Image reference helper. Lets values.yaml use `image.tag: ""` to fall back
to the chart's appVersion, which keeps the chart self-consistent for ad-hoc
deploys while allowing a CI pipeline to pin to an immutable digest.
*/}}
{{- define "phoenix-liveview.image" -}}
{{- $tag := default .Chart.AppVersion .Values.image.tag -}}
{{- printf "%s:%s" .Values.image.repository $tag -}}
{{- end -}}
